# Generated by Django 6.0.5 on 2026-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/'),
        ),
    ]
