# Generated by Django 6.0.5 on 2026-06-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_tutorprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
