# Generated by Django 6.0.5 on 2026-06-12 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutorprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
