# Generated by Django 6.0.5 on 2026-06-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_tutorprofile_created_at_tutorprofile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'ordering': ['display_name']},
        ),
    ]
