# Generated by Django 6.0.5 on 2026-06-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_alter_tutorprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_types', to='tutors.tutorprofile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
