# Generated by Django 6.0.5 on 2026-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_lessontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='skill_level',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('language', 'Language'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
