# Generated by Django 6.0.5 on 2026-06-12 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_lessontype_description_lessontype_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessontype',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
