# Generated by Django 6.0.5 on 2026-06-12 13:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_lessontype_created_at_lessontype_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
