# Generated by Django 6.0.5 on 2026-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0009_alter_lessontype_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontype',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('english', 'English'), ('history', 'History'), ('language', 'Language'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='skill_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20),
        ),
    ]
