# Generated by Django 6.0.5 on 2026-06-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_lessontype_subject_alter_lessontype_skill_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontype',
            options={'ordering': ['lesson_date', 'lesson_time']},
        ),
        migrations.AddField(
            model_name='lessontype',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('creative', 'Creative Arts'), ('languages', 'Languages'), ('music', 'Music'), ('technology', 'Technology'), ('skills', 'Study & Life Skills')], default='academic', max_length=50),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='lesson_date',
            field=models.DateField(default='2026-08-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessontype',
            name='lesson_time',
            field=models.TimeField(default='14:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='subject',
            field=models.CharField(choices=[('mathematics', 'Mathematics'), ('english', 'English'), ('science', 'General Science'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('computer_science', 'Computer Science'), ('history', 'History'), ('geography', 'Geography'), ('business_studies', 'Business Studies'), ('psychology', 'Psychology'), ('art', 'Art'), ('design', 'Design'), ('drama', 'Drama'), ('photography', 'Photography'), ('french', 'French'), ('spanish', 'Spanish'), ('german', 'German'), ('italian', 'Italian'), ('mandarin', 'Mandarin Chinese'), ('japanese', 'Japanese'), ('arabic', 'Arabic'), ('music_theory', 'Music Theory'), ('piano', 'Piano'), ('keyboard', 'Keyboard'), ('guitar_acoustic', 'Acoustic Guitar'), ('guitar_electric', 'Electric Guitar'), ('bass_guitar', 'Bass Guitar'), ('drums', 'Drums'), ('violin', 'Violin'), ('voice', 'Singing / Vocals'), ('coding', 'Programming'), ('web_development', 'Web Development'), ('data_science', 'Data Science'), ('study_skills', 'Study Skills'), ('exam_preparation', 'Exam Preparation')], max_length=50),
        ),
    ]
