# Generated by Django 6.0.5 on 2026-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0011_alter_lessontype_options_lessontype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='lesson_delivery_info',
            field=models.TextField(blank=True, help_text='Add online lesson link details, contact instructions, or how students should prepare.'),
        ),
    ]
