# Generated by Django 6.0.5 on 2026-06-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0012_tutorprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='lesson_delivery_info',
            field=models.TextField(blank=True, help_text='Add online lesson link details and contact information.'),
        ),
    ]
