# Generated by Django 6.0.5 on 2026-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0013_alter_tutorprofile_lesson_delivery_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('creative', 'Creative Arts'), ('languages', 'Languages'), ('music', 'Music'), ('skills', 'Study & Life Skills'), ('technology', 'Technology')], default='academic', max_length=50),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='skill_level',
            field=models.CharField(choices=[('advanced', 'Advanced'), ('all_levels', 'All Levels'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate')], default='all_levels', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='subject',
            field=models.CharField(choices=[('guitar_acoustic', 'Acoustic Guitar'), ('arabic', 'Arabic'), ('art', 'Art'), ('bass_guitar', 'Bass Guitar'), ('biology', 'Biology'), ('business_studies', 'Business Studies'), ('chemistry', 'Chemistry'), ('computer_science', 'Computer Science'), ('coding', 'Programming'), ('data_science', 'Data Science'), ('design', 'Design'), ('drama', 'Drama'), ('drums', 'Drums'), ('guitar_electric', 'Electric Guitar'), ('english', 'English'), ('exam_preparation', 'Exam Preparation'), ('french', 'French'), ('geography', 'Geography'), ('german', 'German'), ('history', 'History'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('keyboard', 'Keyboard'), ('mandarin', 'Mandarin Chinese'), ('mathematics', 'Mathematics'), ('music_theory', 'Music Theory'), ('photography', 'Photography'), ('physics', 'Physics'), ('piano', 'Piano'), ('psychology', 'Psychology'), ('science', 'General Science'), ('spanish', 'Spanish'), ('study_skills', 'Study Skills'), ('violin', 'Violin'), ('voice', 'Singing / Vocals'), ('web_development', 'Web Development')], max_length=50),
        ),
    ]
